--DROP TABLE IF EXISTS temperature;

--CREATE TABLE temperature (
--  id INT AUTO_INCREMENT  PRIMARY KEY,
--  first_name VARCHAR(250) NOT NULL,
--  last_name VARCHAR(250) NOT NULL,
--  email VARCHAR(250) DEFAULT NULL
--);

--CREATE TABLE temperature (
--
--    id              LONG GENERATED BY DEFAULT AS IDENTITY,
--    deviceUUID      VARCHAR(100),
--    columnTwo       VARCHAR(100),
--    unixTimeStamps  BIGINT,
--    dateTime        VARCHAR(100),
--    temperatureInC  DOUBLE(3,1),
--    PRIMARY KEY (id)
--);
--CREATE TABLE IF NOT EXISTS `Person` (
--    `id`         INTEGER  PRIMARY KEY AUTO_INCREMENT,
--     `first_name` VARCHAR(50) NOT NULL,
--     `age`        INTEGER  NOT NULL
--);

--CREATE TABLE temperature (
--  id BIGINT AUTO_INCREMENT NOT NULL,
--   deviceuuid VARCHAR(255),
--   column_two VARCHAR(255),
--   unix_time_stamps BIGINT,
--   date_time VARCHAR(255),
--   temperature_inc DOUBLE,
--   CONSTRAINT pk_temperature PRIMARY KEY (id)
--);

CREATE TABLE person (
  id BIGINT AUTO_INCREMENT NOT NULL,
   first_name VARCHAR(255),
   age INT,
   CONSTRAINT pk_person PRIMARY KEY (id)
);

--CREATE TABLE temperature (
--  id BIGINT AUTO_INCREMENT NOT NULL,
--   device_uuid VARCHAR(255),
--   column_two VARCHAR(255),
--   unix_time_stamps BIGINT,
--   date_time VARCHAR(255),
--   temperature_in_c DOUBLE,
--   CONSTRAINT pk_temperature PRIMARY KEY (id)
--) AS SELECT * FROM CSVREAD('C:/Users/acynt/Desktop/temperature-v3.csv');
--);

--CREATE TABLE temperature AS SELECT * FROM CSVREAD('C:/Users/acynt/Desktop/temperature-v2.csv');
--INSERT INTO temperature AS SELECT * FROM CSVREAD('C:/Users/acynt/Desktop/temperature-v3.csv');

CREATE TABLE temperature (
  id BIGINT AUTO_INCREMENT NOT NULL,
   device_uuid VARCHAR(255),
   column_two VARCHAR(255),
   unix_time_stamps varchar(255),
   date_time VARCHAR(255),
   temperature_in_c DOUBLE,
   CONSTRAINT pk_temperature PRIMARY KEY (id)
);
